### ISSUE TITLE
No module named 'buck_ext'

### ISSUE THREAD

**Issue by Yunusbcr** [facebookresearch/labgraph#34]
## 🐛 Bug

Upgrading LabGraph with,

`python3.6 -m pip install labgraph -U`

creates `No module named 'buck_ext'` error

## Environment

```
 - LabGraph Version (e.g., 1.0): 1.0.2 (installed via pip)
 - OS (e.g., Linux/Mac/Windows): Ubuntu 20.04
 - Python version: 3.6.15

**Comment by Yunusbcr** [comment]
I was using pip 21.3.1, downgraded to pip 21.1.3 but it still giving me same error.

I have checked the the file "labgraph-2.0.0.tar.gz" which is downloaded from [here](https://files.pythonhosted.org/packages/7d/42/58156f7b993bbcc436a96cb6067682782d6075c86c1e9cc9b30183d0be8a/labgraph-2.0.0.tar.gz) and `buck_ext.py` is missing but I think we should not have dependency to buck if have installation with using PyPI.  

```
yunus@yunus-desktop:~/Documents/labgraph$ python3.6 -m pip --version
pip 21.3.1 from /home/yunus/.local/lib/python3.6/site-packages/pip (python 3.6)
```
```
yunus@yunus-desktop:~/Documents/labgraph$ python3.6 -m pip install labgraph -U
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: labgraph in /home/yunus/.local/lib/python3.6/site-packages (1.0.2)
Collecting labgraph
  Using cached labgraph-2.0.0.tar.gz (95 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_38g6qux/labgraph_407021e876d84f2c90dc605b173b62d0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_38g6qux/labgraph_407021e876d84f2c90dc605b173b62d0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3l0m0_r7
       cwd: /tmp/pip-install-_38g6qux/labgraph_407021e876d84f2c90dc605b173b62d0/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_38g6qux/labgraph_407021e876d84f2c90dc605b173b62d0/setup.py", line 4, in <module>
      from buck_ext import BuckExtension, buck_build_ext
  ModuleNotFoundError: No module named 'buck_ext'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/42/58156f7b993bbcc436a96cb6067682782d6075c86c1e9cc9b30183d0be8a/labgraph-2.0.0.tar.gz#sha256=c7669bb193568c20bb69412c048e94d64779d255d2cab404ed7f14b89f0c165b (from https://pypi.org/simple/labgraph/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
```
yunus@yunus-desktop:~/Documents/labgraph$ python3.6 -m pip install pip==21.1.3
Defaulting to user installation because normal site-packages is not writeable
Collecting pip==21.1.3
  Using cached pip-21.1.3-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.3.1
    Uninstalling pip-21.3.1:
      Successfully uninstalled pip-21.3.1
Successfully installed pip-21.1.3
```
```
yunus@yunus-desktop:~/Documents/labgraph$ python3.6 -m pip --version
pip 21.1.3 from /home/yunus/.local/lib/python3.6/site-packages/pip (python 3.6)
```
```
yunus@yunus-desktop:~/Documents/labgraph$ python3.6 -m pip install labgraph -U
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: labgraph in /home/yunus/.local/lib/python3.6/site-packages (1.0.2)
Collecting labgraph
  Using cached labgraph-2.0.0.tar.gz (95 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3s4dmdrr/labgraph_80406cd204434067b01704b7e4c9a53b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3s4dmdrr/labgraph_80406cd204434067b01704b7e4c9a53b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xb9r_rxt
         cwd: /tmp/pip-install-3s4dmdrr/labgraph_80406cd204434067b01704b7e4c9a53b/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3s4dmdrr/labgraph_80406cd204434067b01704b7e4c9a53b/setup.py", line 4, in <module>
        from buck_ext import BuckExtension, buck_build_ext
    ModuleNotFoundError: No module named 'buck_ext'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/42/58156f7b993bbcc436a96cb6067682782d6075c86c1e9cc9b30183d0be8a/labgraph-2.0.0.tar.gz#sha256=c7669bb193568c20bb69412c048e94d64779d255d2cab404ed7f14b89f0c165b (from https://pypi.org/simple/labgraph/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3.6 -m pip install --upgrade pip' command.
```

**Comment by Yunusbcr** [comment]
I think PyPI does not have labgraph-2.0.0  version of this 
`labgraph-1.0.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`

**Comment by jfResearchEng** [comment]
This is for Linux at this moment; for Windows and Mac, we will not have this problem.

**Comment by jfResearchEng** [comment]
Alternative solution is to build it from the source.

**Comment by jfResearchEng** [comment]
> Is there any plan to add the v2.0.0 equivalent of the above .whl (`labgraph-1.0.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`) to PyPi so that labgraph v2.0.0 may be installed on different linux OSes?

Yes, v2.0.0 equivalent of the above wheels will be supported for linux OSes.

**Comment by pperanich** [comment]
Good to hear that. PyPi does not currently have the corresponding .whl, only wheels for windows and mac.
![Screen Shot 2022-01-07 at 1 08 52 PM](https://user-images.githubusercontent.com/34974315/148587850-2a012ccc-f4f3-4171-9943-7bd52364e1f2.png)

**Comment by jfResearchEng** [comment]
> Good to hear that. PyPi does not currently have the corresponding .whl, only wheels for windows and mac. ![Screen Shot 2022-01-07 at 1 08 52 PM](https://user-images.githubusercontent.com/34974315/148587850-2a012ccc-f4f3-4171-9943-7bd52364e1f2.png).

You can now find an update for LabGraph Linux support. 

I'm going to close this issue for now. If you have further questions, feel free to comment in this thread.
