### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by ksachdeva** [facebookresearch/labgraph#8]
## 🚀 Feature
Support to build on macOS would be highly appreciated.

## Motivation
macOS is one of the primary dev platforms for many developers.

## More information
As such, I gave it a try and after few issues with buck/java8, `python setup.py build` started to proceed but then am stuck at issues with linking errors with `gettext`

Seems other projects have faced it and so far none of the remedies have worked.

**Comment by jfResearchEng** [comment]
Hi ksachdeva,

Can you help us provide more details on how to reproduce this error? An example can be found [here](https://github.com/facebookresearch/labgraph/issues/2).

**Comment by ksachdeva** [comment]
Thanks @jfResearchEng 

Here are the steps:

* I downloaded `buck` from https://github.com/facebook/buck/releases/tag/v2021.01.12.01
* Installed various required dependencies using homebrew (ant, openjdk@8 etc)
* I am using python 3.6 as it is this version that is listed (Have tried both venv and regular install)

Issued
```
python setup.py build
```
Here is the trace I get:

```
running build
running build_py
running build_ext
PARSING BUCK FILES: FINISHED IN 1.0s
CREATING ACTION GRAPH: FINISHED IN 0.0s
Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.6m.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.6m.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.6m.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.6m.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.6m.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.6m.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.6m.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.6m.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.6m.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.6m.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.6m.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.6m.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.6m.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.6m.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.6m.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.6m.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.6m.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.6m.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 100.0% CACHE MISS
BUILDING: FINISHED IN 1.4s (100%) 19/19 JOBS, 3 UPDATED
BUILD FAILED
Command failed with exit code 1.

command: [/usr/bin/g++, @/Users/ksachdeva/Desktop/Dev/exp/labgraph/buck-out/bin/cthulhubindings#default,shared/linker.argsfile]

stderr: Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.6m.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.6m.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.6m.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.6m.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.6m.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.6m.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.6m.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

    When running <c++ link>.
    When building rule //:cthulhubindings#default,shared.
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    "yappi==1.2.5",
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/ksachdeva/Desktop/Dev/exp/labgraph/buck_ext.py", line 39, in build_extensions
    + list(exts_by_target.keys())
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/Users/ksachdeva/.pyenv/versions/3.6.10/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['buck', 'build', '--show-output', '--config-file', 'unix.buckconfig', '//:cthulhubindings#default,shared', '//:labgraph_cpp_bindings#default,shared', '//:MyCPPNodes#default,shared']' returned non-zero exit status 1.
```

**Comment by ksachdeva** [comment]
Hi @jfResearchEng 

Any insights that may help would be appreciated.

Regards & thanks
Kapil

**Comment by jfResearchEng** [comment]
Hi @ksachdeva 

The error information you shared above shows a problem with g++ compiler. Note that the supported compilers used in pybinding11 can be found [here](https://github.com/facebookresearch/labgraph/tree/master/third-party/pybind11).

Mac PyPI is also in the roadmap of LabGraph.

Hope you would be able to use LabGraph soon. Thank you for your patience with LabGraph!

Best,
jf
